import {
  CancelAuth,
  GetAccounts,
  GetAuthSession,
  GetCLISyncFile,
  GetCLISyncStatuses,
  GetHostName,
  GetLocalModelCatalog,
  GetLogs,
  GetModelAliases,
  GetProxyStatus,
  GetState,
  ImportAccounts,
  OpenExternalURL,
  RunAccountAction,
  RunCLISync,
  RunCloudflaredAction,
  RunProxyAction,
  RunQuotaAction,
  RunSystemAction,
  SaveCLISyncFile,
  SetModelAliases,
  StartAuth,
  StartSocialAuth,
  SubmitAuthCode,
  SyncAccountAuth,
  UpdateCloudflaredSettings,
  UpdateProxySettings,
} from '../../../wailsjs/go/main/App'

export const wailsClient = {
  system: {
    getState: GetState,
    getHostName: GetHostName,
    runAction: RunSystemAction,
    openExternalURL: OpenExternalURL,
  },
  logs: {
    getLogs: GetLogs,
  },
  auth: {
    startAuth: StartAuth,
    startSocialAuth: StartSocialAuth,
    getAuthSession: GetAuthSession,
    cancelAuth: CancelAuth,
    submitAuthCode: SubmitAuthCode,
  },
  accounts: {
    getAccounts: GetAccounts,
    importAccounts: ImportAccounts,
    runAction: RunAccountAction,
    runQuotaAction: RunQuotaAction,
    syncAccountAuth: SyncAccountAuth,
  },
  router: {
    getProxyStatus: GetProxyStatus,
    getLocalModelCatalog: GetLocalModelCatalog,
    getCliSyncStatuses: GetCLISyncStatuses,
    runCliSync: RunCLISync,
    getCliSyncFile: GetCLISyncFile,
    saveCliSyncFile: SaveCLISyncFile,
    updateProxySettings: UpdateProxySettings,
    updateCloudflaredSettings: UpdateCloudflaredSettings,
    runProxyAction: RunProxyAction,
    runCloudflaredAction: RunCloudflaredAction,
    getModelAliases: GetModelAliases,
    setModelAliases: SetModelAliases,
  },
}
