// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAuth(arg1, arg2) {
  return window['go']['main']['App']['CancelAuth'](arg1, arg2);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetAuthSession(arg1, arg2) {
  return window['go']['main']['App']['GetAuthSession'](arg1, arg2);
}

export function GetCLISyncFile(arg1) {
  return window['go']['main']['App']['GetCLISyncFile'](arg1);
}

export function GetCLISyncStatuses() {
  return window['go']['main']['App']['GetCLISyncStatuses']();
}

export function GetHostName() {
  return window['go']['main']['App']['GetHostName']();
}

export function GetLocalModelCatalog() {
  return window['go']['main']['App']['GetLocalModelCatalog']();
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetModelAliases() {
  return window['go']['main']['App']['GetModelAliases']();
}

export function GetProxyStatus() {
  return window['go']['main']['App']['GetProxyStatus']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function ImportAccounts(arg1) {
  return window['go']['main']['App']['ImportAccounts'](arg1);
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function RunAccountAction(arg1) {
  return window['go']['main']['App']['RunAccountAction'](arg1);
}

export function RunCLISync(arg1) {
  return window['go']['main']['App']['RunCLISync'](arg1);
}

export function RunCloudflaredAction(arg1) {
  return window['go']['main']['App']['RunCloudflaredAction'](arg1);
}

export function RunProxyAction(arg1) {
  return window['go']['main']['App']['RunProxyAction'](arg1);
}

export function RunQuotaAction(arg1) {
  return window['go']['main']['App']['RunQuotaAction'](arg1);
}

export function RunSystemAction(arg1) {
  return window['go']['main']['App']['RunSystemAction'](arg1);
}

export function SaveCLISyncFile(arg1) {
  return window['go']['main']['App']['SaveCLISyncFile'](arg1);
}

export function SetModelAliases(arg1) {
  return window['go']['main']['App']['SetModelAliases'](arg1);
}

export function StartAuth(arg1) {
  return window['go']['main']['App']['StartAuth'](arg1);
}

export function StartSocialAuth(arg1, arg2) {
  return window['go']['main']['App']['StartSocialAuth'](arg1, arg2);
}

export function SubmitAuthCode(arg1, arg2, arg3) {
  return window['go']['main']['App']['SubmitAuthCode'](arg1, arg2, arg3);
}

export function SyncAccountAuth(arg1, arg2) {
  return window['go']['main']['App']['SyncAccountAuth'](arg1, arg2);
}

export function UpdateCloudflaredSettings(arg1) {
  return window['go']['main']['App']['UpdateCloudflaredSettings'](arg1);
}

export function UpdateProxySettings(arg1) {
  return window['go']['main']['App']['UpdateProxySettings'](arg1);
}
