// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {auth} from '../models';
import {main} from '../models';
import {logger} from '../models';

export function CancelAuth(arg1:string,arg2:string):Promise<void>;

export function GetAccounts():Promise<Array<config.Account>>;

export function GetAuthSession(arg1:string,arg2:string):Promise<auth.AuthSessionView>;

export function GetCLISyncFile(arg1:main.CLISyncFileInput):Promise<string>;

export function GetCLISyncStatuses():Promise<Array<main.CLISyncStatus>>;

export function GetHostName():Promise<string>;

export function GetLocalModelCatalog():Promise<Array<main.ModelCatalogItem>>;

export function GetLogs(arg1:number):Promise<Array<logger.Entry>>;

export function GetModelAliases():Promise<Record<string, string>>;

export function GetProxyStatus():Promise<main.ProxyStatus>;

export function GetState():Promise<main.State>;

export function ImportAccounts(arg1:Array<config.Account>):Promise<number>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function RunAccountAction(arg1:main.RunAccountActionInput):Promise<void>;

export function RunCLISync(arg1:main.RunCLISyncInput):Promise<main.CLISyncResult>;

export function RunCloudflaredAction(arg1:string):Promise<main.ProxyStatus>;

export function RunProxyAction(arg1:string):Promise<void>;

export function RunQuotaAction(arg1:main.RunQuotaActionInput):Promise<void>;

export function RunSystemAction(arg1:main.RunSystemActionInput):Promise<void>;

export function SaveCLISyncFile(arg1:main.SaveCLISyncFileInput):Promise<void>;

export function SetModelAliases(arg1:Record<string, string>):Promise<void>;

export function StartAuth(arg1:string):Promise<auth.AuthStart>;

export function StartSocialAuth(arg1:string,arg2:string):Promise<auth.AuthStart>;

export function SubmitAuthCode(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SyncAccountAuth(arg1:string,arg2:string):Promise<auth.AuthSyncResult>;

export function UpdateCloudflaredSettings(arg1:main.UpdateCloudflaredSettingsInput):Promise<void>;

export function UpdateProxySettings(arg1:main.UpdateProxySettingsInput):Promise<main.ProxySettingsUpdateResult>;
